-- Baseline migration: captures the existing schema created by hibernate ddl-auto=update.
-- Flyway baseline-on-migrate will treat the current production schema as the starting point.

CREATE TABLE IF NOT EXISTS profile (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    bio TEXT,
    email VARCHAR(255),
    location VARCHAR(255),
    github_url VARCHAR(500),
    linkedin_url VARCHAR(500),
    resume_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    tech_stack VARCHAR(500),
    github_url VARCHAR(500),
    live_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
