-- Skill categories (Backend, Database, DevOps & Tools, Frontend).
CREATE TABLE IF NOT EXISTS skill_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon_key VARCHAR(100) DEFAULT 'code',
    accent BOOLEAN DEFAULT FALSE,
    display_order INTEGER DEFAULT 0,
    visible BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
